trailingComma: 'all' #"es5"
tabWidth: 4
semi: false
singleQuote: true
printWidth: 100
overrides:
    - files:
          - '*.json'
          - '*.css'
          - '*.md'
      options:
          tabWidth: 2
