trailingComma: 'all' #"es5"
tabWidth: 4
semi: false
singleQuote: true
printWidth: 100
overrides:
    - files:
          - '*.json'
          - '*.css'
      options:
          tabWidth: 2
    - files: '*.hbs'
      options:
          parser: 'html'
          htmlWhitespaceSensitivity: 'ignore'
          embeddedLanguageFormatting: 'off'
