export function createActorTemplateFields(h) {
    const createAttributeEntry = () =>
        h.schema({
            wert: h.number(0),
            pw: h.number(0),
            kampfPw: h.number(0),
        })

    return {
        gesundheit: h.schema({
            erschoepfung: h.number(0),
            wunden: h.number(0),
            wundabzuege: h.number(0),
            wundenignorieren: h.bool(false),
            display: h.string('Volle Gesundheit'),
            hp: h.schema({
                max: h.number(9),
                value: h.number(9),
                threshold: h.number(0),
            }),
        }),
        energien: h.schema({
            asp: h.schema({ max: h.number(0), value: h.number(0), threshold: h.number(0) }),
            gup: h.schema({ max: h.number(0), value: h.number(0), threshold: h.number(0) }),
            kap: h.schema({ max: h.number(0), value: h.number(0), threshold: h.number(0) }),
        }),
        furcht: h.schema({
            furchtstufe: h.number(0),
            furchtabzuege: h.number(0),
            display: h.string(''),
        }),
        modifikatoren: h.schema({
            manuellermod: h.number(0),
            nahkampfmod: h.number(0),
            verteidigungmod: h.number(0),
        }),
        misc: h.schema({
            selected_kampfstil: h.string('ohne'),
            selected_uebernatuerlicher_stil: h.string('ohne'),
            ist_beritten: h.bool(false),
        }),
        initiative: h.number(0),
        abgeleitete: h.schema({
            globalermod: h.number(0),
            ws: h.number(0),
            ws_stern: h.number(0),
            be: h.number(0),
            be_traglast: h.number(0),
            ws_beine: h.number(0),
            ws_larm: h.number(0),
            ws_rarm: h.number(0),
            ws_bauch: h.number(0),
            ws_brust: h.number(0),
            ws_kopf: h.number(0),
            mr: h.number(0),
            gs: h.number(0),
            ini: h.number(0),
            baseIni: h.number(0),
            dh: h.number(0),
            traglast_intervall: h.number(0),
            traglast: h.number(0),
            asp_zugekauft: h.number(0),
            gasp: h.number(0),
            asp: h.number(0),
            asp_stern: h.number(0),
            kap_zugekauft: h.number(0),
            gkap: h.number(0),
            kap: h.number(0),
            kap_stern: h.number(0),
            zauberer: h.bool(false),
            geweihter: h.bool(false),
            nahkampfmoddisplay: h.string('-'),
            globalermoddisplay: h.string('-'),

            gup_zugekauft: h.number(0),
            ggup: h.number(0),
            gup: h.number(0),
            gup_stern: h.number(0),
            paktierer: h.bool(false),
        }),
        schips: h.schema({
            schips: h.number(4),
            schips_stern: h.number(4),
        }),
        attribute: h.schema({
            CH: createAttributeEntry(),
            FF: createAttributeEntry(),
            GE: createAttributeEntry(),
            IN: createAttributeEntry(),
            KK: createAttributeEntry(),
            KL: createAttributeEntry(),
            KO: createAttributeEntry(),
            MU: createAttributeEntry(),
        }),
        geld: h.schema({
            dukaten: h.number(0),
            silbertaler: h.number(0),
            heller: h.number(0),
            kreuzer: h.number(0),
        }),
    }
}

/**
 * Returns a plain-JS default system object for a held actor, mirroring the
 * HeldActorDataModel schema (model-data/held.js).
 *
 * Use this wherever a complete, persistable system object is needed (e.g. in
 * the XML importer) — TypeDataModel only provides these defaults in-memory and
 * does NOT write them to the database automatically.
 *
 * @returns {Object} Default system data matching HeldActorDataModel
 */
export function createHeldActorSystemDefaults() {
    const attributeDefault = () => ({ wert: 0, pw: 0, kampfPw: 0 })

    return {
        gesundheit: {
            erschoepfung: 0,
            wunden: 0,
            wundabzuege: 0,
            wundenignorieren: false,
            display: 'Volle Gesundheit',
            hp: { max: 9, value: 9, threshold: 0 },
        },
        attribute: {
            CH: attributeDefault(),
            FF: attributeDefault(),
            GE: attributeDefault(),
            IN: attributeDefault(),
            KK: attributeDefault(),
            KL: attributeDefault(),
            KO: attributeDefault(),
            MU: attributeDefault(),
        },
        abgeleitete: {
            globalermod: 0,
            ws: 0,
            ws_stern: 0,
            be: 0,
            be_traglast: 0,
            ws_beine: 0,
            ws_larm: 0,
            ws_rarm: 0,
            ws_bauch: 0,
            ws_brust: 0,
            ws_kopf: 0,
            mr: 0,
            gs: 0,
            ini: 0,
            baseIni: 0,
            dh: 0,
            traglast_intervall: 0,
            traglast: 0,
            asp_zugekauft: 0,
            gasp: 0,
            asp: 0,
            asp_stern: 0,
            kap_zugekauft: 0,
            gkap: 0,
            kap: 0,
            kap_stern: 0,
            zauberer: false,
            geweihter: false,
            nahkampfmoddisplay: '-',
            globalermoddisplay: '-',

            gup_zugekauft: 0,
            ggup: 0,
            gup: 0,
            gup_stern: 0,
            paktierer: false,
        },
        schips: { schips: 4, schips_stern: 4 },
        initiative: 0,
        furcht: { furchtstufe: 0, furchtabzuege: 0, display: '' },
        modifikatoren: { manuellermod: 0, nahkampfmod: 0, verteidigungmod: 0 },
        misc: {
            selected_kampfstil: 'ohne',
            selected_uebernatuerlicher_stil: 'ohne',
            ist_beritten: false,
        },
        geld: { dukaten: 0, silbertaler: 0, heller: 0, kreuzer: 0 },
        getragen: 0,
        notes: '',
    }
}

/**
 * Returns a plain-JS default system object for a kreatur actor, mirroring the
 * KreaturActorDataModel schema (model-data/kreatur.js).
 *
 * @returns {Object} Default system data matching KreaturActorDataModel
 */
export function createKreaturActorSystemDefaults() {
    const attributeDefault = () => ({ wert: 0, pw: 0, kampfPw: 0 })

    return {
        gesundheit: {
            erschoepfung: 0,
            wunden: 0,
            wundabzuege: 0,
            wundenignorieren: false,
            display: 'Volle Gesundheit',
            hp: { max: 9, value: 9, threshold: 0 },
        },
        energien: {
            asp: { max: 0, value: 0, threshold: 0 },
            gup: { max: 0, value: 0, threshold: 0 },
            kap: { max: 0, value: 0, threshold: 0 },
        },
        initiative: 0,
        furcht: { furchtstufe: 0, furchtabzuege: 0, display: '' },
        modifikatoren: { manuellermod: 0, nahkampfmod: 0, verteidigungmod: 0 },
        schips: { schips: 0, schips_stern: 0 },
        attribute: {
            CH: attributeDefault(),
            FF: attributeDefault(),
            GE: attributeDefault(),
            IN: attributeDefault(),
            KK: attributeDefault(),
            KL: attributeDefault(),
            KO: attributeDefault(),
            MU: attributeDefault(),
        },
        additemtype: 'angriff',
        edit: false,
        kreaturentyp: 'humanoid',
        kurzbeschreibung: '',
        kampfwerte: {
            ws: 0,
            ws_stern: 0,
            ini: 0,
            baseIni: 0,
            gs: 1,
            koloss: 0,
            mr: 0,
            gs_schwimmend: 0,
        },
        talente: [],
        freietalente: [],
        kampfunfaehig: '',
        text: '',
        abgeleitete: {
            globalermod: 0,
            ws: 0,
            ws_stern: 0,
            be: 0,
            be_traglast: 0,
            ws_beine: 0,
            ws_larm: 0,
            ws_rarm: 0,
            ws_bauch: 0,
            ws_brust: 0,
            ws_kopf: 0,
            mr: 0,
            gs: 0,
            ini: 0,
            baseIni: 0,
            dh: 0,
            traglast_intervall: 0,
            traglast: 0,
            asp_zugekauft: 0,
            gasp: 0,
            asp: 0,
            asp_stern: 0,
            kap_zugekauft: 0,
            gkap: 0,
            kap: 0,
            kap_stern: 0,
            zauberer: false,
            geweihter: false,
            nahkampfmoddisplay: '-',
            globalermoddisplay: '-',
        },
        displayWerte: {
            globalermod: 0,
            ws: 0,
            ws_stern: 0,
            be: 0,
            be_traglast: 0,
            ws_beine: 0,
            ws_larm: 0,
            ws_rarm: 0,
            ws_bauch: 0,
            ws_brust: 0,
            ws_kopf: 0,
            mr: 0,
            gs: 0,
            ini: 0,
            baseIni: 0,
            dh: 0,
            traglast_intervall: 0,
            traglast: 0,
            asp_zugekauft: 0,
            gasp: 0,
            asp: 0,
            asp_stern: 0,
            kap_zugekauft: 0,
            gkap: 0,
            kap: 0,
            kap_stern: 0,
            zauberer: false,
            geweihter: false,
            nahkampfmoddisplay: '-',
            globalermoddisplay: '-',
        },
    }
}
