name: Lint and Format Check

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '.eslintrc*'
      - '.prettierrc*'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            js:
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.ts'
              - '**/*.tsx'
            prettier:
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.ts'
              - '**/*.json'
              - '**/*.css'
              - '**/*.md'

      - name: Run ESLint
        if: steps.filter.outputs.js == 'true'
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier
        if: steps.filter.outputs.prettier == 'true'
        run: npx prettier --check . --config .prettierrc.yaml